services:
  accounts:
    image: "anilkvyas2021/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - anilkvyas2021
  loans:
    image: "anilkvyas2021/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - anilkvyas2021
  cards:
    image: "anilkvyas2021/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - anilkvyas2021
networks:
  anilkvyas2021:
    driver: "bridge"
